export const CREATE_CATEGORY_FAIL ='CREATE_CATEGORY_FAIL'
export const CREATE_CATEGORY_REQUEST ='CREATE_CATEGORY_REQUEST'
export const CREATE_CATEGORY_SUCCESS ='CREATE_CATEGORY_SUCCESS '
export const CREATE_CATEGORY_RESET = 'CREATE_CATEGORY_RESET'

export const GET_CATEGORY_FAIL ='GET_CATEGORY_FAIL'
export const GET_CATEGORY_REQUEST ='GET_CATEGORY_REQUEST'
export const GET_CATEGORY_SUCCESS ='GET_CATEGORY_SUCCESS '
export const GET_CATEGORY_RESET = 'GET_CATEGORY_RESET'

export const DELETE_CATEGORY_FAIL ='DELETE_CATEGORY_FAIL'
export const DELETE_CATEGORY_REQUEST ='DELETE_CATEGORY_REQUEST'
export const DELETE_CATEGORY_SUCCESS ='DELETE_CATEGORY_SUCCESS '
export const DELETE_CATEGORY_RESET = 'DELETE_CATEGORY_RESET'